### ISSUE TITLE
Complete / Uncomplete Feature

### ISSUE THREAD

**Issue by hepcat72** [hendrik-scholz/node-red-icloud#2]
Hey!  This is really cool!  I'm looking forward to playing around with this!  It looks promising to be able to replace the Siri Shortcut automation I created to grab reminder due dates on a cron job.  I've been re-vamping a little project I created long ago to motion-sensor-triggered spoken reminders during certain times of certain days.  I had replaced my Applescript version of the Siri Shortcut because Applescript doesn't (yet) support reminder folders and sub-tasks.  Plus, the applescript was too slow.  But automating a Siri Shortcut to run once an hour is annoying.  This would be much better.

How fast does this execute to retrieve a set of reminders from a specific list?  If it runs very fast, I may not need to cron it at all and grab due dates on the fly.

I have another little project that needs to be triggered by reminder completion.  I imagine that that would have to be accomplished by polling?

But also, I have a couple other little projects that involve un-completing or completing reminders.  Do you plan to add any reminder editing features?

**Comment by hendrik-scholz** [comment]
Hi. Thank you for your message. I haven't tested this project in years. So I'm not sure if it still works with the current version of Node.js and Node-RED. Apart from that, the API might have changed and won't work with the current iCloud API.

I'm thinking about creating a new project based on the current version of Node.js using https://expressjs.com/. As for triggers, I prefer message brokers over polling. See https://github.com/hendrik-scholz/iot-device-information. There is one component that publishes a message to an MQTT broker. Since I don't know the iCloud edit API for reminders, I'm not sure how much effort it is to implement this feature. I think it's a useful feature, though.

**Comment by hepcat72** [comment]
I'll probably just stick with my annoying Siri Shortcut automation then.  Too fragile otherwise.  I was thinking I'd use one of my spare phones to do it so I'm not bothered by shortcut notifications.

I've never been a fan of message brokers honestly, though I know they're hot now.  You can't post any question about automation on reddit without multiple people recommending MQTT. Though I do like the fact that messages get delivered later if the recipient is offline when the message is sent, I have not yet had need for multiple message recipients.  And, the broker is another component that can fail and I have not encountered a case where the recipient being offline isn't a problem unto itself that needs to be solved.  I like the simplicity of a webhook.  It's just as fast, in my testing.  One of these days though, I'm going to need multiple recipients or tolerance for a spotty recipient and I'm going to wish I'd gone through the trouble of setting up a broker.  Are there broker relays for secure access off your LAN?  I can't live without my webhook-relay account.

**Comment by hendrik-scholz** [comment]
I created a new project for a REST API similar to the API in this project. See https://github.com/hendrik-scholz/icloud-api/issues for the features I've planned so far. I think I'll start working on that project in August or September.
